spring:
  application:
    name: "lucas"

  datasource:
    url: jdbc:mysql://localhost:3306/tododb
    username: developer
    password: "1234567"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10



  jpa:
    hibernate:
      ddl-auto: update  # ou 'create', 'create-drop' dependendo do seu ambiente de desenvolvimento
    show-sql: false  # Exibe as consultas SQL no console para depuração
    properties:
      hibernate:
        format_sql: true
api:
  security:
    token: "${JWT_SECRET:my-secret-key}"

server:
  error:
    include-stacktrace: on_param
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
      path: /public/swagger